# Assignment 1

# Sanjoi Sethi (18BCE2261)

# Implementing a Trivial ML Model

In [1]:
import sklearn.datasets
import numpy as np

In [2]:
cancer_ds=sklearn.datasets.load_breast_cancer()

# Organising X and Y

In [3]:
X=cancer_ds.data
Y=cancer_ds.target

In [4]:
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

# Checking No. of Rows and columns

In [5]:
print(X.shape, Y.shape)

(569, 30) (569,)


# Data->Dataframe

In [11]:
import pandas as pd
data=pd.DataFrame(cancer_ds.data,columns=cancer_ds.feature_names)

# Rename the Target Variable

In [12]:
data['class']=cancer_ds.target

# Investigate

In [13]:
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

# Displaying all the Statistical Values of the data

In [14]:
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

# How Many Malignant and Benign

In [15]:
print(data['class'].value_counts())

1    357
0    212
Name: class, dtype: int64


In [16]:
print(cancer_ds.target_names)

['malignant' 'benign']


# Implementing groupby

In [18]:
#Groupby calculates the mean of all the rows whose target value was either 0 or 1

In [19]:
data.groupby('class').mean()

mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class                                                                      
0           141.370330  1422.286321          0.144845           0.374824   
1            87.005938   558.899440          0.124959           0.182673   

       worst concavity  worst concave points  worst symmetry  \
class                                                          
0             0.450606              0.182237        0.323468   
1             0.166238              0.074444        0.270246   

       worst fractal dimension  
class                           
0                     0.091530  
1                     0.079442  

[2 rows x 30 columns]

# TRAIN TEST SPLIT

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X=data.drop('class',axis=1)
Y=data['class']

In [23]:
type(X)

pandas.core.frame.DataFrame

In [24]:
#Magical Line of Code to split a dataset

In [39]:
X_train, X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.1, stratify=Y, random_state=10)

In [40]:
print(Y.shape, Y_train.shape, Y_test.shape)

(569,) (512,) (57,)


In [41]:
print(X_train.mean(), X_test.mean(), X.mean())

mean radius                 14.119902
mean texture                19.275898
mean perimeter              91.879395
mean area                  654.603711
mean smoothness              0.096161
mean compactness             0.103251
mean concavity               0.087585
mean concave points          0.048536
mean symmetry                0.181293
mean fractal dimension       0.062691
radius error                 0.403297
texture error                1.218786
perimeter error              2.849795
area error                  40.127699
smoothness error             0.007072
compactness error            0.025176
concavity error              0.031683
concave points error         0.011771
symmetry error               0.020537
fractal dimension error      0.003751
worst radius                16.233904
worst texture               25.619766
worst perimeter            106.947520
worst area                 877.067188
worst smoothness             0.131886
worst compactness            0.250044
worst concav

# Binarised Input

In [43]:
X_binarised_Train=X_train.apply(pd.cut,bins=2,labels=[1,0])

In [48]:
X_train.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
535        20.55         20.86          137.80     1308.0          0.10460   
338        10.05         17.53           64.41      310.8          0.10070   
503        23.09         19.83          152.10     1682.0          0.09342   
26         14.58         21.53           97.41      644.8          0.10540   
158        12.06         12.74           76.84      448.6          0.09311   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
535           0.17390         0.20850              0.13220         0.2127   
338           0.07326         0.02511              0.01775         0.1890   
503           0.12750         0.16760              0.10030         0.1505   
26            0.18680         0.14250              0.08783         0.2252   
158           0.05241         0.01972              0.01963         0.1590   

     mean fractal dimension  ...  worst radius  worst texture  \
535                 0.06251  ...         24.30          25.48   
338                 0.06331  ...         11.16          26.84   
503                 0.05484  ...         30.79          23.87   
26                  0.06924  ...         17.62          33.21   
158                 0.05907  ...         13.14          18.41   

     worst perimeter  worst area  worst smoothness  worst compactness  \
535           160.20      1809.0            0.1268             0.3135   
338            71.98       384.0            0.1402             0.1402   
503           211.50      2782.0            0.1199             0.3625   
26            122.40       896.9            0.1525             0.6643   
158            84.08       532.8            0.1275             0.1232   

     worst concavity  worst concave points  worst symmetry  \
535          0.44330               0.21480          0.3077   
338          0.10550               0.06499          0.2894   
503          0.37940               0.22640          0.2908   
26           0.55390               0.27010          0.4264   
158          0.08636               0.07025          0.2514   

     worst fractal dimension  
535                  0.07569  
338                  0.07664  
503                  0.07277  
26                   0.12750  
158                  0.07898  

[5 rows x 30 columns]

In [50]:
X_binarised_Train.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
535           0            1              0         1               1   
338           1            1              1         1               1   
503           0            1              0         0               1   
26            1            1              1         1               1   
158           1            1              1         1               1   

    mean compactness mean concavity mean concave points mean symmetry  \
535                1              1                   0             0   
338                1              1                   1             1   
503                1              1                   1             1   
26                 0              1                   1             0   
158                1              1                   1             1   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
535                      1  ...            0             1               0   
338                      1  ...            1             1               1   
503                      1  ...            0             1               0   
26                       1  ...            1             0               1   
158                      1  ...            1             1               1   

    worst area worst smoothness worst compactness worst concavity  \
535          1                1                 1               1   
338          1                1                 1               1   
503          0                1                 1               1   
26           1                0                 0               1   
158          1                1                 1               1   

    worst concave points worst symmetry worst fractal dimension  
535                    0              1                       1  
338                    1              1                       1  
503                    0              1                       1  
26                     0              0                       0  
158                    1              1                       1  

[5 rows x 30 columns]

In [51]:
X_binarised_Test=X_test.apply(pd.cut,bins=2,labels=[1,0])

In [52]:
X_test.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
563       20.920         25.09          143.00     1347.0          0.10990   
347       14.760         14.74           94.87      668.7          0.08875   
44        13.170         21.81           85.42      531.5          0.09714   
289       11.370         18.89           72.17      396.0          0.08713   
424        9.742         19.12           61.93      289.7          0.10750   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
563           0.22360        0.317400              0.14740         0.2149   
347           0.07780        0.046080              0.03528         0.1521   
44            0.10470        0.082590              0.05252         0.1746   
289           0.05008        0.023990              0.02173         0.2013   
424           0.08333        0.008934              0.01967         0.2538   

     mean fractal dimension  ...  worst radius  worst texture  \
563                 0.06879  ...         24.29          29.41   
347                 0.05912  ...         17.27          17.93   
44                  0.06177  ...         16.23          29.89   
289                 0.05955  ...         12.36          26.14   
424                 0.07029  ...         11.21          23.17   

     worst perimeter  worst area  worst smoothness  worst compactness  \
563           179.10      1819.0            0.1407            0.41860   
347           114.20       880.8            0.1220            0.20090   
44            105.50       740.7            0.1503            0.39040   
289            79.29       459.3            0.1118            0.09708   
424            71.79       380.9            0.1398            0.13520   

     worst concavity  worst concave points  worst symmetry  \
563          0.65990               0.25420          0.2929   
347          0.21510               0.12510          0.3109   
44           0.37280               0.16070          0.3693   
289          0.07529               0.06203          0.3267   
424          0.02085               0.04589          0.3196   

     worst fractal dimension  
563                  0.09873  
347                  0.08187  
44                   0.09618  
289                  0.06994  
424                  0.08009  

[5 rows x 30 columns]

In [53]:
X_binarised_Test.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
563           0            0              0         0               0   
347           1            1              1         1               1   
44            1            0              1         1               1   
289           1            1              1         1               1   
424           1            1              1         1               0   

    mean compactness mean concavity mean concave points mean symmetry  \
563                0              0                   0             0   
347                1              1                   1             1   
44                 1              1                   1             1   
289                1              1                   1             0   
424                1              1                   1             0   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
563                      0  ...            0             1               0   
347                      1  ...            1             1               1   
44                       1  ...            1             0               1   
289                      1  ...            1             1               1   
424                      0  ...            1             1               1   

    worst area worst smoothness worst compactness worst concavity  \
563          0                0                 1               0   
347          1                1                 1               1   
44           1                0                 1               1   
289          1                1                 1               1   
424          1                0                 1               1   

    worst concave points worst symmetry worst fractal dimension  
563                    0              1                       1  
347                    1              1                       1  
44                     0              0                       1  
289                    1              1                       1  
424                    1              1                       1  

[5 rows x 30 columns]

# Type of X_binarised_Test

In [55]:
type(X_binarised_Test)

pandas.core.frame.DataFrame

# Convert to arrays

In [56]:
X_binarised_Train=X_binarised_Train.values
X_binarised_Test=X_binarised_Test.values

In [57]:
type(X_binarised_Train)

numpy.ndarray

In [58]:
type(X_binarised_Test)

numpy.ndarray

# ML Model

In [82]:
b=10
import random
i = random.randint(0, X_train.shape[0])
print(i)

if(np.sum(X_binarised_Train[i,:])>=b):
    print('ML Model says its Malignant')
else:
    print('ML Model says its Benign')
    
if(Y_train[i]==1):
    print('Actual O/P is Malignant')
else:
    print('Actual O/P is Benign')

170
ML Model says its Malignant
Actual O/P is Malignant


In [91]:
b=3
import random
i = random.randint(0, X_train.shape[0])
print(i)

if(np.sum(X_binarised_Train[i,:])>=b):
    print('ML Model says its Malignant')
else:
    print('ML Model says its Benign')
    
if(Y_train[i]==1):
    print('Actual O/P is Malignant')
else:
    print('Actual O/P is Benign')

197
ML Model says its Malignant
Actual O/P is Benign


# Checking the accuracy of the model for different value of b

In [92]:
#b is the threshold value that can take up a value as the no. of features present.
#Here, b can take up a total of 32 values (0-31)
#The accuracy will be calculated for each value of b, unlike what we have done above, where we were assuming a random value of b.

In [100]:
for b in range(32):
    total=0
    count=0
    for i in range(len(X_binarised_Train)):
        if(np.sum(X_binarised_Train[i,:])>=b):
            predicted=1
        else:
            predicted=0

        if(Y_train.iloc[i]==1):
            actual=1
        else:
            actual=0
        if(predicted==actual):
            count=count+1
        total=total+1
    accuracy=(count/total)*100
    print("For Threshold Value: ",b," accuracy determined is: ",accuracy)

For Threshold Value:  0  accuracy determined is:  62.6953125
For Threshold Value:  1  accuracy determined is:  62.6953125
For Threshold Value:  2  accuracy determined is:  62.6953125
For Threshold Value:  3  accuracy determined is:  62.6953125
For Threshold Value:  4  accuracy determined is:  62.6953125
For Threshold Value:  5  accuracy determined is:  62.6953125
For Threshold Value:  6  accuracy determined is:  62.6953125
For Threshold Value:  7  accuracy determined is:  62.6953125
For Threshold Value:  8  accuracy determined is:  62.6953125
For Threshold Value:  9  accuracy determined is:  62.6953125
For Threshold Value:  10  accuracy determined is:  62.6953125
For Threshold Value:  11  accuracy determined is:  62.6953125
For Threshold Value:  12  accuracy determined is:  62.6953125
For Threshold Value:  13  accuracy determined is:  62.890625
For Threshold Value:  14  accuracy determined is:  63.4765625
For Threshold Value:  15  accuracy determined is:  63.8671875
For Threshold Value