In [1]:
import pandas as pd
import numpy as np

# Load Data

In [2]:
data=pd.read_csv('crx.data',header=None)

# Create variable names for our dataset

In [3]:
varnames=['A'+str(s) for s in range(1,17)]

# Add Column Names

In [4]:
data.columns=varnames

# Replace ? with np.nan

In [5]:
data=data.replace('?',np.nan)

# re-cast some variable types to its correct type

In [6]:
data['A2']=data['A2'].astype('float')

# Encode target to binary

In [7]:
data['A16']=data['A16'].map({'+':1, '-':0})

# To check our dataset

In [8]:
data

A1     A2      A3 A4 A5  A6  A7    A8 A9 A10  A11 A12 A13    A14  A15  A16
0    b  30.83   0.000  u  g   w   v  1.25  t   t    1   f   g  00202    0    1
1    a  58.67   4.460  u  g   q   h  3.04  t   t    6   f   g  00043  560    1
2    a  24.50   0.500  u  g   q   h  1.50  t   f    0   f   g  00280  824    1
3    b  27.83   1.540  u  g   w   v  3.75  t   t    5   t   g  00100    3    1
4    b  20.17   5.625  u  g   w   v  1.71  t   f    0   f   s  00120    0    1
..  ..    ...     ... .. ..  ..  ..   ... ..  ..  ...  ..  ..    ...  ...  ...
685  b  21.08  10.085  y  p   e   h  1.25  f   f    0   f   g  00260    0    0
686  a  22.67   0.750  u  g   c   v  2.00  f   t    2   t   g  00200  394    0
687  a  25.25  13.500  y  p  ff  ff  2.00  f   t    1   t   g  00200    1    0
688  b  17.92   0.205  u  g  aa   v  0.04  f   f    0   f   g  00280  750    0
689  b  35.00   3.375  u  g   c   h  8.29  f   f    0   t   g  00000    0    0

[690 rows x 16 columns]

# To check data types of the columns

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A1      678 non-null    object 
 1   A2      678 non-null    float64
 2   A3      690 non-null    float64
 3   A4      684 non-null    object 
 4   A5      684 non-null    object 
 5   A6      681 non-null    object 
 6   A7      681 non-null    object 
 7   A8      690 non-null    float64
 8   A9      690 non-null    object 
 9   A10     690 non-null    object 
 10  A11     690 non-null    int64  
 11  A12     690 non-null    object 
 12  A13     690 non-null    object 
 13  A14     677 non-null    object 
 14  A15     690 non-null    int64  
 15  A16     690 non-null    int64  
dtypes: float64(3), int64(3), object(10)
memory usage: 86.4+ KB


# To check the first five rows of our dataset

In [10]:
data.head()

A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15  A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  00202    0    1
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g  00043  560    1
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  00280  824    1
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  00100    3    1
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  00120    0    1

In [12]:
data.head(20)

A1     A2      A3 A4 A5  A6 A7     A8 A9 A10  A11 A12 A13    A14    A15  \
0   b  30.83   0.000  u  g   w  v  1.250  t   t    1   f   g  00202      0   
1   a  58.67   4.460  u  g   q  h  3.040  t   t    6   f   g  00043    560   
2   a  24.50   0.500  u  g   q  h  1.500  t   f    0   f   g  00280    824   
3   b  27.83   1.540  u  g   w  v  3.750  t   t    5   t   g  00100      3   
4   b  20.17   5.625  u  g   w  v  1.710  t   f    0   f   s  00120      0   
5   b  32.08   4.000  u  g   m  v  2.500  t   f    0   t   g  00360      0   
6   b  33.17   1.040  u  g   r  h  6.500  t   f    0   t   g  00164  31285   
7   a  22.92  11.585  u  g  cc  v  0.040  t   f    0   f   g  00080   1349   
8   b  54.42   0.500  y  p   k  h  3.960  t   f    0   f   g  00180    314   
9   b  42.50   4.915  y  p   w  v  3.165  t   f    0   t   g  00052   1442   
10  b  22.08   0.830  u  g   c  h  2.165  f   f    0   t   g  00128      0   
11  b  29.92   1.835  u  g   c  h  4.335  t   f    0   f   g  00260    200   
12  a  38.25   6.000  u  g   k  v  1.000  t   f    0   t   g  00000      0   
13  b  48.08   6.040  u  g   k  v  0.040  f   f    0   f   g  00000   2690   
14  a  45.83  10.500  u  g   q  v  5.000  t   t    7   t   g  00000      0   
15  b  36.67   4.415  y  p   k  v  0.250  t   t   10   t   g  00320      0   
16  b  28.25   0.875  u  g   m  v  0.960  t   t    3   t   g  00396      0   
17  a  23.25   5.875  u  g   q  v  3.170  t   t   10   f   g  00120    245   
18  b  21.83   0.250  u  g   d  h  0.665  t   f    0   t   g  00000      0   
19  a  19.17   8.585  u  g  cc  h  0.750  t   t    7   f   g  00096      0   

    A16  
0     1  
1     1  
2     1  
3     1  
4     1  
5     1  
6     1  
7     1  
8     1  
9     1  
10    1  
11    1  
12    1  
13    1  
14    1  
15    1  
16    1  
17    1  
18    1  
19    1

# To check the last five rows of our dataset

In [11]:
data.tail()

A1     A2      A3 A4 A5  A6  A7    A8 A9 A10  A11 A12 A13    A14  A15  A16
685  b  21.08  10.085  y  p   e   h  1.25  f   f    0   f   g  00260    0    0
686  a  22.67   0.750  u  g   c   v  2.00  f   t    2   t   g  00200  394    0
687  a  25.25  13.500  y  p  ff  ff  2.00  f   t    1   t   g  00200    1    0
688  b  17.92   0.205  u  g  aa   v  0.04  f   f    0   f   g  00280  750    0
689  b  35.00   3.375  u  g   c   h  8.29  f   f    0   t   g  00000    0    0

In [13]:
data.tail(25)

A1     A2      A3 A4 A5  A6  A7     A8 A9 A10  A11 A12 A13    A14  A15  \
665    b  31.83   0.040  y  p   m   v  0.040  f   f    0   f   g  00000    0   
666    a  21.75  11.750  u  g   c   v  0.250  f   f    0   t   g  00180    0   
667    a  17.92   0.540  u  g   c   v  1.750  f   t    1   t   g  00080    5   
668    b  30.33   0.500  u  g   d   h  0.085  f   f    0   t   s  00252    0   
669    b  51.83   2.040  y  p  ff  ff  1.500  f   f    0   f   g  00120    1   
670    b  47.17   5.835  u  g   w   v  5.500  f   f    0   f   g  00465  150   
671    b  25.83  12.835  u  g  cc   v  0.500  f   f    0   f   g  00000    2   
672    a  50.25   0.835  u  g  aa   v  0.500  f   f    0   t   g  00240  117   
673  NaN  29.50   2.000  y  p   e   h  2.000  f   f    0   f   g  00256   17   
674    a  37.33   2.500  u  g   i   h  0.210  f   f    0   f   g  00260  246   
675    a  41.58   1.040  u  g  aa   v  0.665  f   f    0   f   g  00240  237   
676    a  30.58  10.665  u  g   q   h  0.085  f   t   12   t   g  00129    3   
677    b  19.42   7.250  u  g   m   v  0.040  f   t    1   f   g  00100    1   
678    a  17.92  10.210  u  g  ff  ff  0.000  f   f    0   f   g  00000   50   
679    a  20.08   1.250  u  g   c   v  0.000  f   f    0   f   g  00000    0   
680    b  19.50   0.290  u  g   k   v  0.290  f   f    0   f   g  00280  364   
681    b  27.83   1.000  y  p   d   h  3.000  f   f    0   f   g  00176  537   
682    b  17.08   3.290  u  g   i   v  0.335  f   f    0   t   g  00140    2   
683    b  36.42   0.750  y  p   d   v  0.585  f   f    0   f   g  00240    3   
684    b  40.58   3.290  u  g   m   v  3.500  f   f    0   t   s  00400    0   
685    b  21.08  10.085  y  p   e   h  1.250  f   f    0   f   g  00260    0   
686    a  22.67   0.750  u  g   c   v  2.000  f   t    2   t   g  00200  394   
687    a  25.25  13.500  y  p  ff  ff  2.000  f   t    1   t   g  00200    1   
688    b  17.92   0.205  u  g  aa   v  0.040  f   f    0   f   g  00280  750   
689    b  35.00   3.375  u  g   c   h  8.290  f   f    0   t   g  00000    0   

     A16  
665    0  
666    0  
667    0  
668    0  
669    0  
670    0  
671    0  
672    0  
673    0  
674    0  
675    0  
676    0  
677    0  
678    0  
679    0  
680    0  
681    0  
682    0  
683    0  
684    0  
685    0  
686    0  
687    0  
688    0  
689    0

# Save The Data

In [14]:
data.to_csv('creditApproval.csv',index=False)

# Find the categorical Variables

In [15]:
cat_columns=[c for c in data.columns if data[c].dtypes=='O']

In [16]:
data[cat_columns].head()

A1 A4 A5 A6 A7 A9 A10 A12 A13    A14
0  b  u  g  w  v  t   t   f   g  00202
1  a  u  g  q  h  t   t   f   g  00043
2  a  u  g  q  h  t   f   f   g  00280
3  b  u  g  w  v  t   t   t   g  00100
4  b  u  g  w  v  t   f   f   s  00120

In [18]:
cat_columns1=[c for c in data.columns if data[c].dtypes!='O']

In [19]:
data[cat_columns1].head()

A2     A3    A8  A11  A15  A16
0  30.83  0.000  1.25    1    0    1
1  58.67  4.460  3.04    6  560    1
2  24.50  0.500  1.50    0  824    1
3  27.83  1.540  3.75    5    3    1
4  20.17  5.625  1.71    0    0    1

# Task 2 Variables

# Loading the dataset

In [20]:
data=pd.read_csv('loan.csv')

In [21]:
data.head()

customer_id  disbursed_amount  interest market    employment time_employed  \
0            0           23201.5   15.4840      C       Teacher     <=5 years   
1            1            7425.0   11.2032      B    Accountant     <=5 years   
2            2           11150.0    8.5100      A  Statistician     <=5 years   
3            3            7600.0    5.8656      A         Other     <=5 years   
4            4           31960.0   18.7392      E    Bus driver      >5 years   

  householder    income date_issued  target        loan_purpose  \
0        RENT   84600.0  2013-06-11       0  Debt consolidation   
1       OWNER  102000.0  2014-05-08       0        Car purchase   
2        RENT   69840.0  2013-10-26       0  Debt consolidation   
3        RENT  100386.0  2015-08-20       0  Debt consolidation   
4        RENT   95040.0  2014-07-22       0  Debt consolidation   

   number_open_accounts date_last_payment  number_credit_lines_12  
0                   4.0        2016-01-14                     NaN  
1                  13.0        2016-01-25                     NaN  
2                   8.0        2014-09-26                     NaN  
3                  20.0        2016-01-26                     NaN  
4                  14.0        2016-01-11                     NaN

In [23]:
data.shape

(10000, 14)

In [24]:
#Variables -> Numerical and Categorical
# 1) Numerical:
#    - Discrete: 2,3,1 (Eg.: No. of students)
#    - Continuous: 2.5,1.5,11.50 (Eg.: No. of hours)

# 2) Categorical:
#    - Nominal: Names
#    - Ordinal: Sunday-Saturday [1,2,...,7]
#               True/False [0,1]

# Continuous Numerical Variables

In [25]:
data['disbursed_amount'].unique()

array([23201.5 ,  7425.  , 11150.  , ...,  6279.  , 12894.75, 25584.  ])

In [26]:
data['interest'].unique()

array([15.484 , 11.2032,  8.51  , ..., 12.9195, 11.2332, 11.0019])

In [27]:
data['income'].unique()

array([ 84600.  , 102000.  ,  69840.  , ..., 228420.  , 133950.  ,
        55941.84])

# Categorical Variables

In [28]:
data['householder'].unique()

array(['RENT', 'OWNER', 'MORTGAGE'], dtype=object)

In [33]:
data['householder'].value_counts()

MORTGAGE    4957
RENT        4055
OWNER        988
Name: householder, dtype: int64

In [36]:
data['employment'].unique()

array(['Teacher', 'Accountant', 'Statistician', 'Other', 'Bus driver',
       'Secretary', 'Software developer', 'Nurse', 'Taxi driver', nan,
       'Civil Servant', 'Dentist'], dtype=object)

In [37]:
data['loan_purpose'].value_counts()

Debt consolidation    8214
Other                  880
Home improvements      615
Car purchase            90
Health                  87
Holidays                48
Moving home             47
Wedding                 19
Name: loan_purpose, dtype: int64

In [34]:
data['loan_purpose'].unique()

array(['Debt consolidation', 'Car purchase', 'Other', 'Home improvements',
       'Moving home', 'Health', 'Holidays', 'Wedding'], dtype=object)

In [35]:
data['loan_purpose'].value_counts()

Debt consolidation    8214
Other                  880
Home improvements      615
Car purchase            90
Health                  87
Holidays                48
Moving home             47
Wedding                 19
Name: loan_purpose, dtype: int64

# Dates

In [38]:
data['date_issued'].dtypes

dtype('O')

In [39]:
data['date_issued_dt']=pd.to_datetime(data['date_issued'])

In [40]:
data.head()

customer_id  disbursed_amount  interest market    employment time_employed  \
0            0           23201.5   15.4840      C       Teacher     <=5 years   
1            1            7425.0   11.2032      B    Accountant     <=5 years   
2            2           11150.0    8.5100      A  Statistician     <=5 years   
3            3            7600.0    5.8656      A         Other     <=5 years   
4            4           31960.0   18.7392      E    Bus driver      >5 years   

  householder    income date_issued  target        loan_purpose  \
0        RENT   84600.0  2013-06-11       0  Debt consolidation   
1       OWNER  102000.0  2014-05-08       0        Car purchase   
2        RENT   69840.0  2013-10-26       0  Debt consolidation   
3        RENT  100386.0  2015-08-20       0  Debt consolidation   
4        RENT   95040.0  2014-07-22       0  Debt consolidation   

   number_open_accounts date_last_payment  number_credit_lines_12  \
0                   4.0        2016-01-14                     NaN   
1                  13.0        2016-01-25                     NaN   
2                   8.0        2014-09-26                     NaN   
3                  20.0        2016-01-26                     NaN   
4                  14.0        2016-01-11                     NaN   

  date_issued_dt  
0     2013-06-11  
1     2014-05-08  
2     2013-10-26  
3     2015-08-20  
4     2014-07-22

In [41]:
data['month']=data['date_issued_dt'].dt.month

In [42]:
data.head()

customer_id  disbursed_amount  interest market    employment time_employed  \
0            0           23201.5   15.4840      C       Teacher     <=5 years   
1            1            7425.0   11.2032      B    Accountant     <=5 years   
2            2           11150.0    8.5100      A  Statistician     <=5 years   
3            3            7600.0    5.8656      A         Other     <=5 years   
4            4           31960.0   18.7392      E    Bus driver      >5 years   

  householder    income date_issued  target        loan_purpose  \
0        RENT   84600.0  2013-06-11       0  Debt consolidation   
1       OWNER  102000.0  2014-05-08       0        Car purchase   
2        RENT   69840.0  2013-10-26       0  Debt consolidation   
3        RENT  100386.0  2015-08-20       0  Debt consolidation   
4        RENT   95040.0  2014-07-22       0  Debt consolidation   

   number_open_accounts date_last_payment  number_credit_lines_12  \
0                   4.0        2016-01-14                     NaN   
1                  13.0        2016-01-25                     NaN   
2                   8.0        2014-09-26                     NaN   
3                  20.0        2016-01-26                     NaN   
4                  14.0        2016-01-11                     NaN   

  date_issued_dt  month  
0     2013-06-11      6  
1     2014-05-08      5  
2     2013-10-26     10  
3     2015-08-20      8  
4     2014-07-22      7

In [43]:
data.shape

(10000, 16)